Roster options and add fix
BSData/phalanx pull request #53
Opened 2022-09-14 04:07 UTC by jlueck6

Change RosterState to cascade through the components. Afaik, this fixes all prior issues with selection adding and makes things kind of 'just work' when roster state changes.
Adding is still weird in that it doesn't grab all the Category and other info on the add, needs a fix.

RosterOperations for adding/changing CostLimits, and renaming the roster in the brand-new Options tab

2022-09-19 15:45 UTC, jlueck6 commented
Bringing this back to draft. I've got another change set now in which my Git branch isn't like 4 commits behind WHAM.Source et al, and I've started using Symbols for the Add rather than directly traversing Nodes everywhere.

Got a wireframe of a wireframe for Selection editing/routing that I'll be converting into Symbols, then I'll reopen once that's updated

2022-09-20 22:07 UTC, amis92 requested changes
Let's pair-code some evening over the RosterOperations.

2022-09-22 01:54 UTC, jlueck6 commented on global.json
> +    "version": "6.0.109",
The dangers of not feeling like looking up the .Net webpage... and promising to not commit a kludge fix

2022-09-22 02:04 UTC, jlueck6 commented on src/Phalanx.App/Pages/Editing/RosterAddMenu.razor
> +        @foreach (var force in Editor.State.Compilation.GlobalNamespace.Rosters[0].Forces)
At some point, it might be good to have a toggle or two, and/or some sorting for catalogues and forces, for now, which is almost what this code was trying to now. For now, I agree, simplify and remove these excess iterations

2022-10-04 21:39 UTC, amis92 approved these changes

2022-10-10 14:16 UTC, merged